#!/bin/sh

set -e

PREFIX="$(cd "$(dirname "$(which "$0")")" && cd .. && pwd)"
EM_PREFIX="$PREFIX/lib/emscripten"
EMCC="$EM_PREFIX/emcc"
BASENAME="$(basename "$0")"
TARGET="$EM_PREFIX/$BASENAME"

PYS="$(ls "$PREFIX/bin" | grep '^python[0-9].[0-9]\{1,\}$' | sort -r)"

if [ -z "$PYS" ]; then
  echo "Failed to find a Python interpreter"
  exit 1
fi

export PYTHON="$(echo $PYS | awk '{print $1}')"
export LLVM="$EM_PREFIX/llvm/bin"
export BINARYEN="$EM_PREFIX/binaryen"

if [ ! -e "$HOME/.emscripten" ]; then
  "$EMCC" >/dev/null 2>&1 || true
  "$EMCC" >/dev/null 2>&1 || true
fi

exec "$TARGET" "$@"

